source "http://rubygems.org"

gem "rake"
gem "rack"
gem "foreman"
gem "jekyll"
gem "jekyll-assets"
gem "haml"
gem "compass"
gem "zurb-foundation"
gem "coffee-script"
gem "uglifier"
gem "pygments.rb"
gem "rdiscount"
gem "sinatra"
